test

diff --git a/.github/workflows/test-unit.yml b/.github/workflows/test-unit.yml
--- a/.github/workflows/test-unit.yml
+++ b/.github/workflows/test-unit.yml
@@ -159,6 +159,7 @@ jobs:
           php -r '(new PDO("mysql:host=mysql5", "root", "atk4_pass_root"))->exec("GRANT USAGE ON *.* TO '"'"'atk4_test_user'"'"'@'"'"'%'"'"' WITH MAX_USER_CONNECTIONS 5");'
           php -r '(new PDO("mysql:host=mariadb", "root", "atk4_pass_root"))->exec("ALTER USER '"'"'atk4_test_user'"'"'@'"'"'%'"'"' WITH MAX_USER_CONNECTIONS 5");'
           php -r '(new PDO("pgsql:host=postgres;dbname=atk4_test", "atk4_test_user", "atk4_pass"))->exec("ALTER ROLE atk4_test_user CONNECTION LIMIT 1");'
+          cat /usr/lib/oracle/setup.sh
           /usr/lib/oracle/setup.sh
           if [ -n "$LOG_COVERAGE" ]; then mkdir coverage; echo "memory_limit = 192M" > /usr/local/etc/php/conf.d/custom-memory-limit.ini; fi
 
@@ -243,6 +244,36 @@ jobs:
           php -d opcache.enable_cli=1 vendor/bin/phpunit --exclude-group none $(if [ -n "$LOG_COVERAGE" ]; then echo --coverage-text; else echo --no-coverage; fi) --fail-on-warning --fail-on-risky $(if vendor/bin/phpunit --version | grep -q '^PHPUnit 9\.'; then echo -v; else echo --fail-on-notice --fail-on-deprecation --display-notices --display-deprecations --display-warnings --display-errors --display-incomplete --display-skipped; fi)
           if [ -n "$LOG_COVERAGE" ]; then mv coverage/phpunit.cov coverage/phpunit-mssql.cov; fi
 
+      - name: Test Oracle connections
+        run: |
+          php <<'PHP'
+          <?php
+
+          $connections = [];
+
+          for ($i = 1; $i <= 100; ++$i) {
+              $c = @oci_connect(
+                  'system',
+                  'atk4_pass',
+                  'oracle:1521/FREE'
+              );
+
+              if (!$c) {
+                  echo "FAILED at connection #$i\n";
+                  print_r(oci_error());
+                  break;
+              }
+
+              $connections[] = $c;
+              echo "Connection #$i OK\n";
+          }
+
+          echo "Successful connections: " . count($connections) . "\n";
+
+          foreach ($connections as $c) {
+              oci_close($c);
+          }
+          PHP
       - name: Oracle diagnostics
         if: success() || failure()
         run: |
@@ -264,27 +295,27 @@ jobs:
               print_r($r);
           }
           '
-      - name: "Run tests: Oracle - PDO (only for coverage or cron)"
-        if: (success() || failure()) && (env.LOG_COVERAGE || github.event_name == 'schedule')
-        env:
-          DB_DSN: "pdo_oci:dbname=oracle/free"
-          DB_USER: system
-          DB_PASSWORD: atk4_pass
-          NLS_LANG: AMERICAN_AMERICA.AL32UTF8
-        run: |
-          php -d opcache.enable_cli=1 vendor/bin/phpunit --exclude-group none $(if [ -n "$LOG_COVERAGE" ]; then echo --coverage-text; else echo --no-coverage; fi) --fail-on-warning --fail-on-risky $(if vendor/bin/phpunit --version | grep -q '^PHPUnit 9\.'; then echo -v; else echo --fail-on-notice --fail-on-deprecation --display-notices --display-deprecations --display-warnings --display-errors --display-incomplete --display-skipped; fi)
-          if [ -n "$LOG_COVERAGE" ]; then mv coverage/phpunit.cov coverage/phpunit-oracle-pdo.cov; fi
+      #- name: "Run tests: Oracle - PDO (only for coverage or cron)"
+      #  if: (success() || failure()) && (env.LOG_COVERAGE || github.event_name == 'schedule')
+      #  env:
+      #    DB_DSN: "pdo_oci:dbname=oracle/free"
+      #    DB_USER: system
+      #    DB_PASSWORD: atk4_pass
+      #    NLS_LANG: AMERICAN_AMERICA.AL32UTF8
+      #  run: |
+      #    php -d opcache.enable_cli=1 vendor/bin/phpunit --exclude-group none $(if [ -n "$LOG_COVERAGE" ]; then echo --coverage-text; else echo --no-coverage; fi) --fail-on-warning --fail-on-risky $(if vendor/bin/phpunit --version | grep -q '^PHPUnit 9\.'; then echo -v; else echo --fail-on-notice --fail-on-deprecation --display-notices --display-deprecations --display-warnings --display-errors --display-incomplete --display-skipped; fi)
+      #    if [ -n "$LOG_COVERAGE" ]; then mv coverage/phpunit.cov coverage/phpunit-oracle-pdo.cov; fi
 
-      - name: "Run tests: Oracle - OCI8"
-        if: success() || failure()
-        env:
-          DB_DSN: "oci8:dbname=oracle/free"
-          DB_USER: system
-          DB_PASSWORD: atk4_pass
-          NLS_LANG: AMERICAN_AMERICA.AL32UTF8
-        run: |
-          php -d opcache.enable_cli=1 vendor/bin/phpunit --exclude-group none $(if [ -n "$LOG_COVERAGE" ]; then echo --coverage-text; else echo --no-coverage; fi) --fail-on-warning --fail-on-risky $(if vendor/bin/phpunit --version | grep -q '^PHPUnit 9\.'; then echo -v; else echo --fail-on-notice --fail-on-deprecation --display-notices --display-deprecations --display-warnings --display-errors --display-incomplete --display-skipped; fi)
-          if [ -n "$LOG_COVERAGE" ]; then mv coverage/phpunit.cov coverage/phpunit-oracle-oci8.cov; fi
+      #- name: "Run tests: Oracle - OCI8"
+      #  if: success() || failure()
+      #  env:
+      #    DB_DSN: "oci8:dbname=oracle/free"
+      #    DB_USER: system
+      #    DB_PASSWORD: atk4_pass
+      #    NLS_LANG: AMERICAN_AMERICA.AL32UTF8
+      #  run: |
+      #    php -d opcache.enable_cli=1 vendor/bin/phpunit --exclude-group none $(if [ -n "$LOG_COVERAGE" ]; then echo --coverage-text; else echo --no-coverage; fi) --fail-on-warning --fail-on-risky $(if vendor/bin/phpunit --version | grep -q '^PHPUnit 9\.'; then echo -v; else echo --fail-on-notice --fail-on-deprecation --display-notices --display-deprecations --display-warnings --display-errors --display-incomplete --display-skipped; fi)
+      #    if [ -n "$LOG_COVERAGE" ]; then mv coverage/phpunit.cov coverage/phpunit-oracle-oci8.cov; fi
 
       - name: Upload coverage logs 1/2 (only for coverage)
         if: env.LOG_COVERAGE
