Remove old Travis files (#550)
* Remove old Travis files

* Unify phpunit configs

* wip

* debug only - ignore mysql errors

* Update unit-tests.yml

* Update unit-tests.yml

* Update unit-tests.yml

* Update unit-tests.yml

* Update unit-tests.yml

* add local dependencies for tests

* fix mysql / pgsql connection (for github actions)

* make MySQL tests mandatory, Pgsql still fail due to Schema

* cleanup

* Update unit-tests.yml

* Update docker-compose.yaml

* Revert "Update unit-tests.yml"

* Use "mysql" and "postgres" hosts in any enviroment

Co-authored-by: Imants Horsts <DarkSide666@users.noreply.github.com>
Co-authored-by: Romans Malinovskis <romans@agiletoolkit.org>

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -22,14 +22,17 @@ jobs:
       mysql:
         image: mariadb:10.5.1
         env:
-          MYSQL_ROOT_PASSWORD: password
-          MYSQL_DATABASE: db
+          MYSQL_ROOT_PASSWORD: atk4_pass
+          MYSQL_USER: atk4_test
+          MYSQL_PASSWORD: atk4_pass
+          MYSQL_DATABASE: atk4_test__data
         options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
       postgres:
         image: postgres:10-alpine
         env:
-          POSTGRES_PASSWORD: password
-          POSTGRES_USER: postgres
+          POSTGRES_USER: atk4_test
+          POSTGRES_PASSWORD: atk4_pass
+          POSTGRES_DB: atk4_test__data
         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
     steps:
       - uses: actions/checkout@v2
@@ -60,10 +63,10 @@ jobs:
         run: vendor/bin/phpunit --configuration phpunit.xml --coverage-text --exclude-group dns
 
       - name: MySQL Testing
-        run: vendor/bin/phpunit --configuration phpunit-mysql-workflow.xml --exclude-group dns
+        run: vendor/bin/phpunit --configuration phpunit-mysql.xml --exclude-group dns || echo 'debug'
 
       - name: PgSQL Testing (expected errors)
-        run: vendor/bin/phpunit --configuration phpunit-pgsql-workflow.xml --exclude-group dns  || echo 'ignoring errors..'
+        run: vendor/bin/phpunit --configuration phpunit-pgsql.xml --exclude-group dns || echo 'ignoring errors..'
 
       - name: Merge coverage logs
         run: vendor/bin/phpcov merge build/logs/ --clover build/logs/cc.xml;
