Remove old Travis files

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -55,10 +55,10 @@ jobs:
         run: vendor/bin/phpunit --configuration phpunit.xml --coverage-text --exclude-group dns
 
       - name: MySQL Testing
-        run: vendor/bin/phpunit --configuration phpunit-mysql-workflow.xml --exclude-group dns
+        run: vendor/bin/phpunit --configuration phpunit-mysql.xml --exclude-group dns
 
       - name: PgSQL Testing (expected errors)
-        run: vendor/bin/phpunit --configuration phpunit-pgsql-workflow.xml --exclude-group dns  || echo 'ignoring errors..'
+        run: vendor/bin/phpunit --configuration phpunit-pgsql.xml --exclude-group dns || echo 'ignoring errors..'
 
       - name: Merge coverage logs
         run: vendor/bin/phpcov merge build/logs/ --clover build/logs/cc.xml;
